name: Feature Request
description: Suggest an idea for this project
title: "[Request]: [Short Descriptive Title] "
labels: ["request","fresh"]
assignees:
  - depatchedmode
projects: ["everywhere-computer/projects/1"]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to suggest a feature. Please fill out the following information to help us understand your proposal. And then give it a short, descriptive title. The more thoughtful and complete your submission is, the more likely it is to get engagement from the team and community."

  - type: textarea
    attributes:
      label: "Feature Description"
      description: "Describe the feature and how it adds value."
      placeholder: "Describe your feature here."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Use Cases"
      description: "Describe at least one specific and critical scenario where this feature would be used."
      placeholder: "Example use case for the feature."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Signals of Success"
      description: "What might we observe, or directly measure in the system, that would indicate the use cases are being addressed."
      placeholder: "List things we could measure or observe"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Current Workarounds (optional)"
      description: "How do you get the job done right now, without the functionality you're describing?"
      placeholder: "Let us know how you currently address the problem."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Suggested Implementation (Optional)"
      description: "If you have ideas on how this feature could be implemented, please share them here."
      placeholder: "Your implementation suggestions."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Job Stories (Optional)"
      description: "Job stories are a variant of user stories we use to detail the outcomes the feature needs to support, for whom, in what situations. It will typically get fleshed out over time."
      placeholder: "As a {role}, when {something happens}, I want to {do this job} so that I can {achieve a specific outcome}"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Additional Context (Optional)"
      description: "Add any other context, screenshots or links to related issues here."
      placeholder: "Any additional information."
    validations:
      required: false
